### ISSUE TITLE
Invisible Ores - Cragrim 

### ISSUE THREAD

**Issue by MiningMark48** [MiningMark48/Dimensional-Ores#4]
I found a bug that causes invisible ores. Gif video:

http://i.imgur.com/hO9t85k.gif 

Config to replicate dimensionalores.cfg: https://pastebin.com/fCMFYLqE

Setting overworld world gen ores to false appears to fix it!

I had only sulfur and quartz enabled for the overworld so maybe its related to that. Maybe you can find exactly what causes it.

Workaround:

```
"overworld ores world gen" {
    # Should overword ores be generated? [default: true]
    B:"Overworld Ores World Gen"=false
}
```
This took quite a while to debug and narrow down which mod caused this but I finally got it! :)

It might also be related to this line (but I havent tested it)

 `B:config.add_overworld_tin.title=false`
 The formatting for that line doesn't match the other options.

------
**Copied from the CurseForge project page.**

Posted by @cragrim

**Comment by cragrim** [comment]
Some more info:
Might have been caused by interaction with another mod that changes ore spawning. I couln't figure out which combination of mods cause it only that changing configs in dimensional ores removed the bug.

I used World Stripper for debugging and checking. Its really handy for checking ore configs.
https://mods.curse.com/mc-mods/minecraft/250603-world-stripper#t1:other-downloads

Sorry I cant be much more help
Thanks again for smashing bugs!
